### ISSUE TITLE
Build fails with duplicate symbols error for simulator

### ISSUE THREAD

**Issue by devKrishnan** [SocketMobile/singleentry-ios#1]
Ld /Users/krishnan/Library/Developer/Xcode/DerivedData/Business-frderrseiornslbqomwerlboiaki/Build/Products/Debug-iphonesimulator/ScanAPI.framework/ScanAPI normal i386
    cd /DeveloperPath/Pods
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Users/krishnan/Desktop/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Users/krishnan/Desktop/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Users/krishnan/Desktop/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch i386 -dynamiclib -isysroot /Users/krishnan/Desktop/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -L/Users/krishnan/Library/Developer/Xcode/DerivedData/Business-frderrseiornslbqomwerlboiaki/Build/Products/Debug-iphonesimulator -L/DeveloperPath/Pods/../ScanApiSDK-10.2.227/lib -F/Users/krishnan/Library/Developer/Xcode/DerivedData/Business-frderrseiornslbqomwerlboiaki/Build/Products/Debug-iphonesimulator -filelist /Users/krishnan/Library/Developer/Xcode/DerivedData/Business-frderrseiornslbqomwerlboiaki/Build/Intermediates/Pods.build/Debug-iphonesimulator/ScanAPI.build/Objects-normal/i386/ScanAPI.LinkFileList -install_name @rpath/ScanAPI.framework/ScanAPI -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -objc_abi_version -Xlinker 2 -lScanApiCore -lc++ -framework AVFoundation -framework AudioToolbox -framework ExternalAccessory -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -stdlib=libc++ -mios-simulator-version-min=8.0 -framework AVFoundation -framework AudioToolbox -framework ExternalAccessory -framework Foundation -single_module -compatibility_version 10 -current_version 10.2.227 -Xlinker -dependency_info -Xlinker /Users/krishnan/Library/Developer/Xcode/DerivedData/Business-frderrseiornslbqomwerlboiaki/Build/Intermediates/Pods.build/Debug-iphonesimulator/ScanAPI.build/Objects-normal/i386/ScanAPI_dependency_info.dat -o /Users/krishnan/Library/Developer/Xcode/DerivedData/Business-frderrseiornslbqomwerlboiaki/Build/Products/Debug-iphonesimulator/ScanAPI.framework/ScanAPI

duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktRuntimeLib.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktRuntimeLib.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktBuffer.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktBuffer.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktList.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktList.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktQueue.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktQueue.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktSimpleXml.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktSimpleXml.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktUtilities.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktUtilities.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktPath.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktPath.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktEnumerator.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktEnumerator.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktStream.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktStream.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktStringArray.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktStringArray.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktProtocolInterface.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktProtocolInterface.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktTranslator.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktTranslator.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktSsiProtocol.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktSsiProtocol.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktDeviceObject.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktDeviceObject.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktDeviceObjectInterface.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktDeviceObjectInterface.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktListener.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktListener.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktScanCore.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktScanCore.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanVersionImplementation.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanVersionImplementation.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanObjectImplementation.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanObjectImplementation.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanMsgImplementation.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanMsgImplementation.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanApiImplementation.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanApiImplementation.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SoftScanController.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SoftScanController.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanDeviceImplementation.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanDeviceImplementation.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanSymbologyImplementation.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanSymbologyImplementation.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanPropertyImplementation.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanPropertyImplementation.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktTransport.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktTransport.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktIAPProtocol.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktIAPProtocol.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(RunLoopSource.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(RunLoopSource.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktSerialTransport.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktSerialTransport.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(BluetoothData.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(BluetoothData.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(BluetoothHelper.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(BluetoothHelper.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktIscpBaseProtocol.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktIscpBaseProtocol.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktSoftScanDeviceObject.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktSoftScanDeviceObject.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(AccessoryMonitor.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(AccessoryMonitor.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktAccessoryEnumerator.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktAccessoryEnumerator.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanEventImplementation.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanEventImplementation.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanDecodedDataImplementation.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(ISktScanDecodedDataImplementation.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(Observer.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(Observer.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktPlatform.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktPlatform.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktEvent.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktEvent.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktIAPSsiProtocol.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktIAPSsiProtocol.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktDeviceInterface.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktDeviceInterface.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktDeviceInterfaceIos.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktDeviceInterfaceIos.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktBtIscpProtocol.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktBtIscpProtocol.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktConfigXml.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktConfigXml.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(CSktScanAPI.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(CSktScanAPI.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktDeviceConfig.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktDeviceConfig.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktDataEditingProfile.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktDataEditingProfile.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktOperation.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktOperation.o)
duplicate symbol _llvm.cmdline in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktParsingString.o)
duplicate symbol _llvm.embedded.module in:
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktClassFactory.o)
    /DeveloperPath/ScanApiSDK-10.2.227/lib/libScanApiCore.a(SktParsingString.o)
ld: 100 duplicate symbols for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by EricGlaenzer** [comment]
@devKrishnan Make sure you didn't include twice the libScanApi.a in your project when building for the simulator. When installing ScanAPI CocoaPods the library will be automatically added to your project in your workspace.
