### ISSUE TITLE
build fails with current sdk 10.3.55

### ISSUE THREAD

**Issue by afarouk** [SocketMobile/singleentry-ios#2]
/Users/alamgirfarouk/Desktop/Scanner/SingleEntry/SingleEntry/MainViewController.m:578:22: No visible @interface for 'ScanApiHelper' declares the selector 'postSetDataConfirmation:Target:Response:'

**Comment by EricGlaenzer** [comment]
Some ScanApiHelper API has their prototype slightly modified from the previous version. This has been fixed.
