### ISSUE TITLE
Error pod install

### ISSUE THREAD

**Issue by RaviNguyen** [SocketMobile/singleentry-ios#4]
Type pod install, have an error:
 No podspec found for `ScanAPI` in `../ScanApiSDK-10.3.93`
Please support me :)

**Comment by EricGlaenzer** [comment]
Hi Ravi, the ScanAPI SDK needs to be downloaded from Socket Mobile developer portal. I would highly recommend using the new Capture SDK which replaces ScanAPI especially if you are starting a new project.
